---
- name: clone geauxshax-features
  git:
    repo: https://github.com/lsulibraries/geauxshax-features
    dest: "{{ drupal_core_path }}/sites/all/modules/geauxshax-features"
    
- name: Enable features
  command: "drush -y en {{ item }}"
  args:
     chdir: "{{ drupal_core_path }}"
  with_items: "{{ geaux_shax_features }}"

- name: revert features
  command: "drush fr -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ geaux_shax_features }}"
