---
- name: get geaux-shax specific drupal modules
  command: "drush dl -y {{ item  }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ geaux_shax_modules_dl }}"

- name: enable modules for geaux-shax
  command: "drush en -y {{ item }}"
  args:
   chdir: "{{ drupal_core_path }}"
  with_items: "{{ geaux_shax_modules_to_be_enabled }}"

- include: features.yml

- name: Set permission
  file:
    path: "{{ drupal_core_path }}/sites/all/modules/"
    owner: www-data
    recurse: yes

- name: set theme
  command: drush vset theme_default skeletontheme
